# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe90ae6fa89fe9b9682475b295dd3eac32015d6cf0e54d6024c016c0dd2d98ca1e93c56abfc50e9e877a7a7b93d78e157cf3978147546341aaa4ddf46de751ea

test:
  secret_key_base: 19fb306cc5d90a09f00185f36393db62a86893d05a776c647d8f3dcde43ac87a7959e21de3f43e370b59084bc7ee1159f0ab4497d49d76e66e4b2d5f904ef4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
